#Example Configurations
#-----------------------
#Uncomment below and paste your Slack application token
#token: '*unspecified*'
#-----------------------
#Start Channel Configurations
#channels:
#  '#warns-bans':
#    incoming: {}
#    outgoing:
#      gesuit:
#        bans: true
#        warns: true
#        unbans: true
#  admin-chat:
#    outgoing:
#      admin:
#        channel: AdminChat
#        allowRestarts: false
#    incoming: {}
#
