#Example Configurations
#-----------------------
#Uncomment below and paste your Slack application token
#token: '*unspecified*'
#
#-----------------------
#Start Channel Configurations
#channels:
#  '#warns-bans':
#    incoming: {}
#    outgoing:
#      gesuit:
#        bans: true
#        warns: true
#        unbans: true
#  admin-chat:
#    outgoing:
#      admin:
#        channel: AdminChat
#        allowRestarts: false
#    incoming: {}
#
#ticketConfig:
#  MySQL:
#    hostname: localhost
#    hostport: 3306
#    database: simpletickets
#    user: simpletickets
#    password: simpletickets
#    properties:
#      useSSL: false